### ISSUE TITLE
Error "Integrated flux is <= 0"

### ISSUE THREAD

**Issue by mdastro** [spacetelescope/pysynphot#37] opened 2017-05-05 00:38 UTC
Hello @pllim ,

I am trying to calculate the ab magnitude from simulated photometry and I got the following error:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-a4a30df06e08> in <module>()
     19                                              force='extrap')
     20 
---> 21         photometry.append(photometry_i.effstim('abmag'))
     22         print photometry
     23         exit()

/usr/local/lib/python2.7/dist-packages/pysynphot/observation.pyc in effstim(self, fluxunits)
    540             if x.isDensity:
    541                 rate=self.integrate()
--> 542                 self._fluxcheck(rate)
    543                 if x.isMag:
    544                     ans=x.unitResponse(self.bandpass) - 2.5*math.log10(rate)

/usr/local/lib/python2.7/dist-packages/pysynphot/observation.pyc in _fluxcheck(self, totalflux)
    563     def _fluxcheck(self,totalflux):
    564         if totalflux <= 0.0:
--> 565             raise ValueError('Integrated flux is <= 0')
    566         if np.isnan(totalflux):
    567             raise ValueError('Integrated flux is NaN')

**ValueError: Integrated flux is <= 0**
```

Do you have any ideas why this is like this?

Thank you!

**Comment by pllim** [comment] 2017-05-05 14:58
Hi again. As the error said, your total flux is zero or negative. As of why, I cannot tell you until you provide a minimal example to reproduce it along with data files used.

**Comment by mdastro** [comment] 2017-05-08 16:44
Hi @pllim ,
I tried to reproduce the problem and I found that it happens specifically for one of the 12 filters I am using.

The filter, spectrum and python notebook can be found here:
https://github.com/mdastro/Challenge/tree/master/Simplest_Pysynphot

Please ignore the warnings in the beggining. I am travelling and didn't configure pysynphot completely. However, my other notebooks are working even with these warnings.

Thanks again!

**Comment by pllim** [comment] 2017-05-09 15:47
You are getting zero integrated flux because your spectrum does not overlap your bandpass coverage. Plotting them with `matplotlib` shows me the following:

![figure_1](https://cloud.githubusercontent.com/assets/2090236/25859660/35afc760-34ad-11e7-856a-cf2897e62208.png)

**Comment by pllim** [comment] 2017-05-09 15:47
I am closing this as solved. Please re-open if you feel otherwise.

**Closed by pllim** 2017-05-09 15:47 UTC
Labels: question

**Comment by mdastro** [comment] 2017-05-10 12:10
Thank you so much @pllim . Sorry for the stupid question.
