### ISSUE TITLE
k(lambda) of pysynphot

### ISSUE THREAD

**Issue by hahareally** [spacetelescope/pysynphot#150] opened 2023-01-10 13:54 UTC
Hi, I am trying to verify the k(lambda) value of pysynphot(https://training-library.readthedocs.io/en/latest/pysynphot.html).
Assuming E(B-V)=0.2 and a starburst galaxy,
import pysynphot as S
extinct = S.Extinction(0.2, 'xgalsb')
extinct(6563)
0.76

But according to eq.3 of Calzetti2000 (https://iopscience.iop.org/article/10.1086/308692/pdf), 
k(6563A)=3.32
Lintrinsic=Lobservation*10**(0.4 x 3.32 x 0.2)=Lobservation  x 1.84

0.76>>1/1.84

So which value is correct?

ps:  where is the k(lambda) of Cardelli1989 (https://ui.adsabs.harvard.edu/abs/1989ApJ...345..245C/abstract)?

Thank you!

**Comment by pllim** [comment] 2023-01-17 21:29
Hello, looks like this is more of a question for https://github.com/spacetelescope/ins-training-library/issues . If the authors there determines this to be a software bug, please then submit a minimally reproducible example with the expected result.

Furthermore, PySynphot is deprecated, please use https://stsynphot.readthedocs.io/en/latest/

**Comment by pllim** [comment] 2023-01-20 23:58
INS has confirmed that the referenced training page is now defunct. Closing this issue.

**Closed by pllim** 2023-01-20 23:58 UTC
Labels: question
