### ISSUE TITLE
Questions on simulating photometry

### ISSUE THREAD

**Issue by mdastro** [spacetelescope/pysynphot#36] opened 2017-04-05 20:40 UTC
Hi @pllim,

As I explained before, I am using pysynphot for the first time and I was given an example script in order to simulate photometry from SDSS spectra.

The idea is to read the spectra, the response filters, and finally simulate the photometry. The script can be found [here](https://github.com/mdastro/Challenge/blob/master/Coding/sanity_check.ipynb) with the respective error. So that this issue is complete, the code error appears when I use pysynphot for the first time with the `FileBandpass`  command:

```
jpas_filter_bandpass = np.array(np.loadtxt(os.path.join(jpas_filters_path, jpas_filters)))
jpas_filter_bandpass = s.FileBandpass(jpas_filter_bandpass)
```

By the way, the `jpas_filter_bandpass` file is a two-column file with wavelength and flux respectively.

The error:

> AttributeError                            Traceback (most recent call last)
> <ipython-input-5-deec18d20a2e> in <module>()
>       7         jpas_filter_bandpass = np.array(np.loadtxt(os.path.join(jpas_filters_path, jpas_filters)))
>       8         sdss_spectrum        = np.loadtxt(os.path.join(test_specs, each_spectrum), usecols=(0,1))
> ----> 9         jpas_filter_bandpass = s.FileBandpass(jpas_filter_bandpass)
>      10 #         print sdss_spectrum
>      11 #         exit()
> 
> /home/mldantas/miniconda2/lib/python2.7/site-packages/pysynphot/spectrum.pyc in __init__(self, filename, thrucol)
>    2942     """
>    2943     def __init__(self, filename, thrucol=None):
> -> 2944         self.name = locations.irafconvert(filename)
>    2945         self._readThroughputFile(self.name, thrucol)
>    2946 
> 
> /home/mldantas/miniconda2/lib/python2.7/site-packages/pysynphot/locations.pyc in irafconvert(iraffilename)
>     256 
>     257     # remove duplicate separators and extraneous relative paths
> --> 258     iraffilename = os.path.normpath(iraffilename)
>     259 
>     260     #BUG: supports environment variables only as the leading element in the
> 
> /home/mldantas/miniconda2/lib/python2.7/posixpath.pyc in normpath(path)
>     333     if path == '':
>     334         return dot
> --> 335     initial_slashes = path.startswith('/')
>     336     # POSIX allows one or two initial slashes, but treats three or more
>     337     # as single slash.
> 
> AttributeError: 'numpy.ndarray' object has no attribute 'startswith'

Could you please enlighten me on this error?

The nexts steps are the ones commented in the Jupyter Notebook I linked above. The scprit of course is not ready, but I guess you can understand my point.

Thank you!

Maria Luiza

**Comment by pllim** [comment] 2017-04-05 21:13
FileBandpass is used to load given filename, not array. Try ArrayBandpass. The document has API usage info.

**Comment by pllim** [comment] 2017-04-06 12:59
FileBandpass API:
http://pysynphot.readthedocs.io/en/latest/ref_api.html#pysynphot.spectrum.FileSpectralElement

ArrayBandpass API:
http://pysynphot.readthedocs.io/en/latest/ref_api.html#pysynphot.spectrum.ArraySpectralElement

If you read directly from file, not arrays, the file has to follow acceptable formats:
http://pysynphot.readthedocs.io/en/latest/using_pysynphot.html#file-i-o

Usage documentation on bandpass:
http://pysynphot.readthedocs.io/en/latest/bandpass.html

Yes, the actual class name is different because it is aliased to something else in an attempt to be user-friendly on import.

**Comment by mdastro** [comment] 2017-04-06 18:39
Thank you very much @pllim . I will follow your instructions and see if it works.
Cheers!

**Comment by pllim** [comment] 2017-04-06 18:40
If it works, please close this issue. Thank you.

**Comment by mdastro** [comment] 2017-04-06 18:41
Will do.

**Comment by mdastro** [comment] 2017-04-06 20:36
Hi @pllim,

My code seems to be working just fine right now, and the core of it is basically:

```
        jpas_filter_bandpass = s.FileBandpass(os.path.join(jpas_filters_path, jpas_filters))        
#         jpas_filter_bandpass.throughput
        sdss_spectrum        = s.FileSpectrum(os.path.join(test_specs, each_spectrum), keepneg=True)
        photometry_i           = s.Observation(sdss_spectrum, jpas_filter_bandpass, binset=np.arange(3000, 11000, 1), force='extrap') 
```

However, the photometry_i is giving a weird result: 'the path of my spectrum' + 'the name of the filter'. Not a photometry as I expected. Do you have any idea what is going wrong? I really appreciate any help.

Details on this, the code is [here](https://github.com/mdastro/Challenge/blob/master/Coding/sanity_check.ipynb).

Cheers and thanks again!

**Comment by pllim** [comment] 2017-04-06 21:22
Without access to your actual data, it is hard to tell. What are you trying to calculate? What exactly is in your data files (units?)? What is the expected value and what is pysynphot giving you?

There are some assumptions going into pysynphot, e.g., default units if not given, interpolation details, etc. In your notebook, I see a lot of negative flux warnings. Is you flux in mag or what?

**Comment by mdastro** [comment] 2017-04-06 21:45
Hi @pllim,

Thank you for your answer. 

> Without access to your actual data, it is hard to tell. What are you trying to calculate? What  exactly is in your data files (units?)? What is the expected value and what is pysynphot giving you?

I am trying to simulate photometry from SDSS spectra given ~60 narrow band filters. The SDSS spectra is in F_lambda and the units are in _erg s^-1 cm^-2_ . The first column is the wavelength and the second is the flux and **i just realized by answering you that I have 2 more columns in the spectra files**. So, **maybe here is the problem**, how do I use s.Spectrum with a file like that? Is there anyway I can just read the  2 first columns and get s.Spectrum to read it or does it have to be another separate file?

> There are some assumptions going into pysynphot, e.g., default units if not given, interpolation details, etc. In your notebook, I see a lot of negative flux warnings. Is you flux in mag or what?

I guess these negative fluxes are from the bins of the spectrum that have erros. I would like to consider these bins as `NAN` or something like that.

Thanks once again!

**Comment by pllim** [comment] 2017-04-07 14:40
Multiple columns should not be a problem, but only first two are read, the rest ignored.

>  s.FileBandpass(os.path.join(jpas_filters_path, jpas_filters), keepneg=True)

I don't understand how your notebook even worked in the first place. `FileBandpass` has no `keepneg` keyword. It should have raised an exception. Where did you get the pysynphot package? What version are you using?

**Comment by mdastro** [comment] 2017-04-10 20:26
I installed pysynphot using pip. Since it was not working before I contacted you, I also installed cloning the github repo and later deleted it. My version is 0.9.8.5.

I still can't make it run, even removing the keepneg command. :/

**Comment by pllim** [comment] 2017-04-11 14:56
It looks like you use conda but are using the "root" environment, which I do not recommend. I think it is best to start from scratch. Please follow instructions at http://astroconda.readthedocs.io/en/latest/ to create a new environment, then grab pysynphot from our AstroConda channel by doing "conda install pysynphot". The version should be 0.9.8.6, not 0.9.8.5. When you have done that, try again in the astroconda environment (remember to "source activate astroconda" to switch over first).

**Comment by mdastro** [comment] 2017-04-12 17:54
Thanks @pllim . I will do it ASAP and get back to you.

**Comment by mdastro** [comment] 2017-04-12 18:28
@pllim, according to the webpage you sent, I would need to install Astroconda, but is it really necessary to install pysynphot? My system is a 32-bit linux, not 64 as required.

**Comment by pllim** [comment] 2017-04-12 18:32
Then try:
```
pip install git+https://github.com/spacetelescope/pysynphot.git@0.9.8.6
```

**Comment by mdastro** [comment] 2017-04-12 18:49
Done it, the error is still the same. Maybe it would be helpful to check the input files. The filters are like these: https://github.com/mdastro/Challenge/tree/master/Filters/JPAS_Filters
And the spectra like these: https://github.com/mdastro/Challenge/tree/master/Filters/JPAS_Filters

Maybe you can reproduce the problem with the jupyter notebook ?

**Comment by pllim** [comment] 2017-04-13 15:52
Just giving me a bunch of files won't help. I need a specific case that I can reproduce. What exactly are you using for that one case? What is the expected answer, since you claim the value from Pysynphot is wrong?

**Comment by mdastro** [comment] 2017-04-18 17:09
Hi @pllim ,

I created a very simple example of what I am doing and the error is repeated.

I am trying to generate simulated photometry from SDSS spectra for a specific survey (J-PAS). This survey has ~60 filters, which makes it very hard to do several things by hand.

What do I need? Answer: Simulated photometry from a set of filters.
What do I have? Answer: the spectra of the galaxies from which I would like to simulate the photometry. This spectra is from SDSS. Also, I have the filter responses that I need.

The toy example that I created is in [here](https://github.com/mdastro/Challenge/tree/master/Simplest_Pysynphot). When I print what I believe should be the photometry, I get, once again,"the path * the file" (/my_path/0266.51602.001.7xt * /my_path/Jv0915_3495.res ) -- see [this really simple jupyter notebook](https://github.com/mdastro/Challenge/blob/master/Simplest_Pysynphot/Photometry%20Simulation.ipynb) which is possible to reproduce my error, just fix the paths in your machine. The files you need are in the folder I sent in the previous link.

I really appreciate any help.

Thanks a lot again!

**Comment by pllim** [comment] 2017-04-18 17:44
Thanks, that is much more helpful for me. It appears you were close but you stopped right after creating the `Observation` instance. All you needed to do was to actually use the appropriate *methods* of the class instance for your calculations. Please see https://gist.github.com/pllim/9bd61155661768aa4f35a920d652f308

**Comment by pllim** [comment] 2017-04-18 17:51
Also, make sure you pass in the correct units. I have no idea what the unit is supposed to be for your flux column in the source spectrum, however, at a glance, the flux value appears to be too high for FLAM.

http://pysynphot.readthedocs.io/en/latest/using_pysynphot.html#pysynphot-io

**Comment by mdastro** [comment] 2017-04-18 18:42
Thank you so much @pllim . You finally discovered the mystery! :-D
What method you think is best for photometry in flux units,` obs.countrate('flam')`? The result is what I expected. The values are correct; they have been normalized by 10^-17, so it makes sense. 

Thank you very much for your patience!

**Comment by pllim** [comment] 2017-04-18 18:49
There is no such thing as `countrate('flam')` (although it should have raised an exception here when used) -- I think what is happening here is it is passing in "flam" into its `binned` keyword and interpreting it as such.

If you want your result in "flam", use [effstim()](https://pysynphot.readthedocs.io/en/latest/ref_api.html#pysynphot.observation.Observation.effstim).

**Comment by mdastro** [comment] 2017-04-18 18:50
Yes, ok, sorry! Thank you.

**Comment by pllim** [comment] 2017-04-18 18:51
No problem.

**Closed by pllim** 2017-04-18 18:51 UTC
Labels: question
